import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "NextJs App - About",
  description: "Generated by create next app",
}

export default function AboutLayout({
  children,
}: {
    children: React.ReactNode;
}) {
    return <div>
    <p>About layout</p>
    {children}</div>
}
